title: Reuzenarbeid

# Preferred map tiles
# tile_url: https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
tile_url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}'
# tile_url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'

# Preferred IIIF viewer
viewer_base_url: http://uv-v4.netlify.app/uv.html#?manifest=
# viewer_base_url: https://projectmirador.org/embed/?manifest=

# IIIF Server settings
image_base_url: https://dlc.services/iiif-img/7/6/
manifest_base_url: https://dlc.services/iiif-resource/delft/string1string2string3/reuzenarbeid/

collections:
  projects:
    output: false
